language: node_js
node_js: '10'
cache:
  - yarn
  - npm

install:
- npm install -g npx npm-cli-login
- yarn install --non-interactive --pure-lockfile

script:
- yarn run lint
- CI=false yarn run build || travis_terminate 1;
- yarn run test

after_script:
- npm-cli-login -u $NPM_USER -p $NPM_PASS  
