language: node_js
node_js: '10'
cache:
  - yarn
  - npm

install:
- npm install -g npx
- yarn install --non-interactive --pure-lockfile

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: 'Checks and Tests'
      script: ./scripts/build.sh
    - stage: deploy
      name: 'Publish and Release'
      script:
        - ./scripts/build.sh
        - npm install -g npm-cli-login
        - npm-cli-login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL