# Bare kjøre på hovedbranch
if: branch = master

language: node_js
node_js: '10'
cache:
  - yarn
  - npm

install:
- npm install -g npx
- yarn install --non-interactive --pure-lockfile

before_script:
# - yarn run lint

script:
- CI=false yarn run build || travis_terminate 1;