language: node_js
node_js: '10'
cache:
  - yarn
  - npm

install:
- npm install -g npx
- yarn install --non-interactive --pure-lockfile

before_script:
- yarn run test

script:
- CI=false yarn run build || travis_terminate 1;

deploy:
  on:
    branch: master
