language: node_js
node_js: '10'
cache:
  - yarn
  - npm
stages:
- name: deploy
  # require the branch name to be master (note for PRs this is the base branch name)
  if: branch = master

install:
- npm install -g npx
- npm install -g npm-cli-login
- yarn install --non-interactive --pure-lockfile

before_script:
- yarn run test

script:
- CI=false yarn run build || travis_terminate 1;

deploy:
- npm-cli-login -u $NPM_USER -p $NPM_PASS
