language: node_js
node_js: '10'
cache:
  - yarn
  - npm
stages:
- install
- check
- build
- name: publish
  if: branch = master

install:
- npm install -g npx
- npm install -g npm-cli-login
- yarn install --non-interactive --pure-lockfile

check:
- yarn run lint
- yarn run test

build:
- CI=false yarn run build || travis_terminate 1;

publish:
- npm-cli-login -u $NPM_USER -p $NPM_PASS  
