name: CI
on: [push, release]

jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-18.04
    steps:
    - name: Check Out
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Client Dependencies
      run: yarn install --non-interactive --pure-lockfile
    - name: Lint
      run: yarn run lint
    - name: Build
      run: yarn run build
    - name: Test
      run: yarn run test
    - name: Archive build
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

  release-beta:
    name: Deploy
    needs: build
    runs-on: ubuntu-18.04
    env:
      NPM_USER: ${{ secrets.NPM_USER }}
      NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - name: Check Out
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install npm client login
        run: npm install -g npm-cli-login
      - name: Install NP
        run: npm install --global np
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Login to NPM
        run: npm-cli-login -u $NPM_USER -p $NPM_PASSWORD -e $NPM_EMAIL
      - name: NP
        run: np prepatch --tag=dev